### ISSUE TITLE
역할 분담용 이슈 - 역기획

### ISSUE THREAD

**Issue by ALsseL** [wetcod/creativeDesign#8]
- 화면 전체 리스트

번호 | 페이지 번호 | 페이지 명칭 | 용도
:-------: | :-------: | :-------: | :-------:
1 | [~view-01~](https://github.com/wetcod/creativeDesign/blob/master/HW3_ReverseDesignDocument/view01_메인.md) | 메인 화면 | 게이머가 최초 게임에 진입해 만나게되는 화면
2 | [~view-02~](https://github.com/wetcod/creativeDesign/blob/master/HW3_ReverseDesignDocument/view02_게임플레이.md) | 게임플레이 화면 | 게임을 실제로 플레이 하는 화면
3 | [view-03](https://github.com/wetcod/creativeDesign/blob/master/HW3_ReverseDesignDocument/view03_모드.md) | 모드선택 화면 | 게임 모드를 선택하는 화면
4 | [view-04](https://github.com/wetcod/creativeDesign/blob/master/HW3_ReverseDesignDocument/view04_친구.md) | 친구관리 화면 | 친구목록을 관리하는 화면
5 | [view-05](https://github.com/wetcod/creativeDesign/blob/master/HW3_ReverseDesignDocument/view05_초대.md) | 초대관리 화면 | 초대 관리 업무를 수행가능한 화면
6 | [view-06](https://github.com/wetcod/creativeDesign/blob/master/HW3_ReverseDesignDocument/view06_파티.md) | 파티모집 화면 | 파티 모집을 수행하는 화면
7 | [view-07](https://github.com/wetcod/creativeDesign/blob/master/HW3_ReverseDesignDocument/view07_채팅.md) | 채팅 화면 | 다른 유저들과 채팅할 수 있는 화면
8 | [~view-08~](https://github.com/wetcod/creativeDesign/blob/master/HW3_ReverseDesignDocument/view08_시즌.md) | 시즌정보 화면 | 시즌 정보들을 알려주는 화면
9 | [~view-09~](https://github.com/wetcod/creativeDesign/blob/master/HW3_ReverseDesignDocument/view09_클랜.md) | 클랜관리 화면 | 나의 클랜을 관리하는 화면
10 | [~view-10~](https://github.com/wetcod/creativeDesign/blob/master/HW3_ReverseDesignDocument/view10_크루.md) | 크루관리 화면 | 나의 크루를 관리하는 화면
11 | [~view-11~](https://github.com/wetcod/creativeDesign/blob/master/HW3_ReverseDesignDocument/view11_무기고.md) | 무기고화면 | 나의 무기정보를 관리하는 화면
12 | [~view-12~](https://github.com/wetcod/creativeDesign/blob/master/HW3_ReverseDesignDocument/view12_창고.md) | 창고화면 | 나의 복장 등을 관리 하는 화면
13 | [~view-13~](https://github.com/wetcod/creativeDesign/blob/master/HW3_ReverseDesignDocument/view13_랭킹.md) | 랭킹화면 | 게임 랭킹을 확인가능한 화면
14 | [~view-14~](https://github.com/wetcod/creativeDesign/blob/master/HW3_ReverseDesignDocument/view14_미션.md) | 미션화면 | 미션을 관리하는 화면
15 | [~view-15~](https://github.com/wetcod/creativeDesign/blob/master/HW3_ReverseDesignDocument/view15_메일.md) | 메일화면 | 메일을 관리하는 화면
16 | [~view-16~](https://github.com/wetcod/creativeDesign/blob/master/HW3_ReverseDesignDocument/view16_설정.md) | 설정화면 | 설정을 관리하는 화면
17 | [~view-17~](https://github.com/wetcod/creativeDesign/blob/master/HW3_ReverseDesignDocument/view17_개인정보.md) | 개인정보화면 | 유저정보를 관리하는 화면
18 | [~view-18~](https://github.com/wetcod/creativeDesign/blob/master/HW3_ReverseDesignDocument/view18_캐시충전.md) | 캐시충전화면 | 캐시를 충전하는 화면
19 | [~view-19~](https://github.com/wetcod/creativeDesign/blob/master/HW3_ReverseDesignDocument/view19_상점.md) | 상점화면 | 물건등을 구매할 수 있는 화면
20 | [~view-20~](https://github.com/wetcod/creativeDesign/blob/master/HW3_ReverseDesignDocument/view20_.md) | 이벤트화면 | 이벤트를 공지하는 화면

**Comment by ALsseL** [comment]
#9 메인화면/화면하단/무기고/SR 제가 합니다.

**Comment by ALsseL** [comment]
#7 #9 11번 무기고 화면 제가 합니다

**Comment by ardorlife27** [comment]
view-13,14,15,16은 제가 하겠습니다.

**Comment by wetcod** [comment]
View-1,2는 제가 하겠습니다

**Comment by ALsseL** [comment]
#10 #11 #12 #13 8~12는 제가 하겠습니다.

**Comment by codychi37** [comment]
#17 #18 #19 #20 17~20 제가 하겠습니다

**Comment by codychi37** [comment]
view 17~20 제가 하겠습니다
